# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule {
    name = steam-news-float
    match:title = Volume Control
    float = true
}

windowrule {
    name = volume-control-float
    match:title = Steam - News
    float = true
}

windowrule {
    name = space-craft-fullscreen
    match:title = Space Craft
    workspace = 6
    fullscreen = true
}
